#서버 설정
server:
  port: 9090
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 45m
      tracking-modes: cookie
      
#spring:
datasource:
  url: jdbc:mysql://106.10.44.49:3306/bside
  username: bside
  password: bside
  driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:sqlmap/mappers/**/*Mapper.xml

#swagger
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher